---
title: "BCHM421_FinalProject0"
author: "Group C"
date: "2025-12-03"
output:
  html_document:
  runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vroom)
library(shiny)
library(ggplot2)
library(magrittr)
library(DT)
library(bslib)
library(htmltools)
load("ObjectSave.rda")
```

# ```{r, echo=FALSE}
# tags$style(HTML("
# .modal-backdrop.show {
# opacity: 0.6 !important;
# }
# .modal-dialog {
# margin-top: 10vh !important;
# }
# "))
# ```

<!-- ```{r} -->

<!-- cpm_wide <- "/depot/pascuzz-cl/data/bchm_data/human/cpm_wide.txt" -->

<!-- prmt5_results <- "/depot/pascuzz-cl/data/bchm_data/human/prmt5_results.txt" -->

<!-- mep50_results <- "/depot/pascuzz-cl/data/bchm_data/human/mep50_results.txt" -->

<!-- cpm <- vroom(file=file.path(cpm_wide),  -->

<!--                          delim="\t",  -->

<!--                          col_types=NULL) -->

<!-- prmt5 <- vroom(file=file.path(prmt5_results),  -->

<!--                          delim="\t",  -->

<!--                          col_types="cnnnnfc") -->

<!-- mep50 <- vroom(file=file.path(mep50_results),  -->

<!--                          delim="\t",  -->

<!--                          col_types="cnnnnfc") -->

<!-- prmt5 -->

<!-- mep50 -->

<!-- ``` -->

<!-- ## Add silenced gene to RNAseq results -->

<!-- ```{r} -->

<!-- prmt5 <- prmt5 %>% -->

<!--   mutate(silenced = "prmt5") -->

<!-- mep50 <- mep50 %>% -->

<!--   mutate(silenced = "wdr77") -->

<!-- RNAseq <- rbind(prmt5, mep50) -->

<!-- RNAseq -->

<!-- ``` -->

<!-- ## Up regulated genes for GO from PRMT5 and MEP50 -->

<!-- ```{r} -->

<!-- up_genes_prmt5 <- prmt5 %>% -->

<!--   filter(tests == "1") %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- up_genes_prmt5 -->

<!-- write_delim(up_genes_prmt5, "prmt5_up.txt", col_names = FALSE) -->

<!-- up_genes_mep50 <- mep50 %>% -->

<!--   filter(tests == "1") %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- up_genes_mep50 -->

<!-- write_delim(up_genes_mep50, "mep50_up.txt", col_names = FALSE) -->

<!-- down_genes_prmt5 <- prmt5 %>% -->

<!--   filter(tests == "-1") %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- down_genes_prmt5 -->

<!-- write_delim(down_genes_prmt5, "prmt5_down.txt", col_names = FALSE) -->

<!-- down_genes_mep50 <- mep50 %>% -->

<!--   filter(tests == "-1") %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- down_genes_prmt5 -->

<!-- write_delim(down_genes_mep50, "mep50_down.txt", col_names = FALSE) -->

<!-- back_genes_prmt5 <- prmt5 %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- write_delim(back_genes_prmt5, "prmt5_back.txt", col_names=FALSE) -->

<!-- back_genes_mep50 <- mep50 %>% -->

<!--   dplyr::select(SYMBOL) -->

<!-- write_delim(back_genes_mep50, "mep50_back.txt", col_names=FALSE) -->

<!-- ``` -->

<!-- ## Importing GOrilla xls results -->

<!-- ```{r} -->

<!-- GO_mep50_down <- vroom("~/BCHM421_FinalProject0/GOrilla Results/GO_mep50_down.txt", delim="\t", col_names=TRUE) -->

<!-- GO_mep50_up <- vroom("~/BCHM421_FinalProject0/GOrilla Results/GO_mep50_up.txt", delim="\t", col_names=TRUE) -->

<!-- GO_prmt5_down <- vroom("~/BCHM421_FinalProject0/GOrilla Results/GO_prmt5_down.txt", delim="\t", col_names=TRUE) -->

<!-- GO_prmt5_up <- vroom("~/BCHM421_FinalProject0/GOrilla Results/GO_prmt5_up.txt", delim="\t", col_names=TRUE) -->

<!-- GO_mep50_down <- GO_mep50_down %>% -->

<!--   mutate(Group = "wdr77_down") -->

<!-- GO_mep50_up <- GO_mep50_up %>% -->

<!--   mutate(Group = "wdr77_up") -->

<!-- GO_prmt5_up <- GO_prmt5_up %>% -->

<!--   mutate(Group = "prmt5_up") -->

<!-- GO_prmt5_down <- GO_prmt5_down %>% -->

<!--   mutate(Group = "prmt5_down") -->

<!-- GO_mep50_down -->

<!-- GO_mep50_up -->

<!-- GO_prmt5_down -->

<!-- GO_prmt5_up -->

<!-- GO_gene <- rbind(GO_mep50_down, GO_mep50_up, GO_prmt5_down, GO_prmt5_up) -->

<!-- GO_gene -->

<!-- ``` -->

<!-- ## Extracting GO gene symbols -->

<!-- ```{r} -->

<!-- #Function to extract gene symbols -->

<!-- getGorillaSymbols <- function(genes){ -->

<!--   require(dplyr) -->

<!--   require(magrittr) -->

<!--   genes %>%  -->

<!--     str_split(" - ", simplify=FALSE) %>% -->

<!--     c(recursive=TRUE) %>% -->

<!--     str_split(", ") %>% -->

<!--     sapply(tail, 1) %>% -->

<!--     str_trim("both") %>% -->

<!--     extract(1:(length(.) - 1)) %>% -->

<!--     str_remove("\\[") %>% -->

<!--     return(.) -->

<!-- } -->

<!-- prmt5up_genes <- lapply(GO_prmt5_up$Genes, getGorillaSymbols) -->

<!-- names(prmt5up_genes) <- pull(GO_prmt5_up, `GO Term`) -->

<!-- prmt5up_genes <- lapply(prmt5up_genes, function(x)(tibble(Symbol=x))) -->

<!-- prmt5up_genes <- bind_rows(prmt5up_genes, .id="GO_ID") -->

<!-- prmt5up_genes -->

<!-- prmt5down_genes <- lapply(GO_prmt5_down$Genes, getGorillaSymbols) -->

<!-- names(prmt5down_genes) <- pull(GO_prmt5_down, `GO Term`) -->

<!-- prmt5down_genes <- lapply(prmt5down_genes, function(x)(tibble(Symbol=x))) -->

<!-- prmt5down_genes <- bind_rows(prmt5down_genes, .id="GO_ID") -->

<!-- prmt5down_genes -->

<!-- prmt5_geneIndex <- prmt5up_genes %>% -->

<!--   rbind(prmt5down_genes) %>% -->

<!--   mutate(grouping = "prmt5") -->

<!-- prmt5_geneIndex -->

<!-- mep50up_genes <- lapply(GO_mep50_up$Genes, getGorillaSymbols) -->

<!-- names(mep50up_genes) <- pull(GO_mep50_up, `GO Term`) -->

<!-- mep50up_genes <- lapply(mep50up_genes, function(x)(tibble(Symbol=x))) -->

<!-- mep50up_genes <- bind_rows(mep50up_genes, .id="GO_ID") -->

<!-- mep50up_genes -->

<!-- mep50down_genes <- lapply(GO_mep50_down$Genes, getGorillaSymbols) -->

<!-- names(mep50down_genes) <- pull(GO_mep50_down, `GO Term`) -->

<!-- mep50down_genes <- lapply(mep50down_genes, function(x)(tibble(Symbol=x))) -->

<!-- mep50down_genes <- bind_rows(mep50down_genes, .id="GO_ID") -->

<!-- mep50down_genes -->

<!-- geneIndex <- mep50up_genes %>% -->

<!--   rbind(prmt5down_genes) %>% -->

<!--   mutate(grouping = "mep50") -->

<!-- geneIndex -->

<!-- ``` -->

## Make widget for RNAseq data table

```{r, echo=FALSE}
renderDataTable({
  datatable(RNAseq,
            filter = list(position = "top", clear = FALSE, plain = TRUE),
            extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           pageLength = 10,
                           buttons = list(extend='collection',
                                          buttons=c('csv', 'excel'),
                                          text='Download'))
  ) %>%
    formatSignif(columns=c('logFC', 'logCPM', 'PValue', 'FDR'), digits=4)
})
```

## Make multi-RNAseq symbol select graph
```{r, echo=FALSE}
ui <- page_fixed(
actionButton("show", "?")
)

server <- function(input, output, session) {

observe({
showModal(
modalDialog(
title = "Column plog charting logFC values for select genes base on the RNAseq data table.",
easyClose = TRUE,
"The following column plot displays the log of the fold-change (e.g., a 2-fold change is represented by +1 on the y-axis, whereas a 0.5-fold change, meaning expression is halved, is represnted by -1 on the y-axis) of the expression of our genes of interest, PRMT5 and WDR77. The symbol selected by the user via the dropdown box represents the gene that was silenced for that given trial. Upon selecting this gene, the user can see both the change in expression of the PRMT5 gene (represented by the pink column) and the change in expression of the WDR77 gene (represented by the blue column) from baseline. Users can select multiple silenced genes to observe the PRMT5 and WDR77 expression results of multiple trials."
)
)
}) |>
bindEvent(input$show)

}

shinyApp(ui, server)
```

```{r, echo = FALSE}
selectInput(
inputId = "symbol",
label = "Select Symbol(s):",
multiple = TRUE,
choices = unique(RNAseq$SYMBOL)
)

# Filter tibble in terms of SYMBOL

renderPlot({
req(input$symbol)
  
RNAseq %>%
  filter(SYMBOL %in% input$symbol) %>%
  ggplot(aes(x = SYMBOL, y = logFC)) +
  geom_col(aes(fill = silenced),
           position = "dodge"
  ) +
  labs(
    title = "Results for Select Gene",
    y = "logFC",
    x = "SYMBOL"
  ) +
  theme_gray()
})
```

## Format GO tibble for widget creation

```{r, echo=FALSE}
GO_widget <- GO_gene %>%
  rename(GO_ID = `GO Term`) %>%
  rename(FDR = `FDR q-value`) %>%
  select(GO_ID, Group, Description, FDR, Enrichment)

GO_widget
```

## GO data table
```{r}
ui <- page_fixed(
actionButton("show", "?")
)

server <- function(input, output, session) {

observe({
showModal(
modalDialog(
title = "Gene ontology data table.",
easyClose = TRUE,
"The user can interact with this data via the search bars, which allow them to type and look up any of the displayed variables (e.g, GO_ID, Group, Description, FDR, and Enrichment). The user can also use the single search bar above the interactive data frame to return results related to the user's request. Additionally, the user can select how many entries to display on the screen via the drop-down list. This goes up to 100 entries. Lastly, the user can export the data table in two different ways—as a .csv or an Excel file.

The 'GO_ID' refers to the Gene Ontology identification. The 'Group' variable indicates whether a gene is up- or down-regulated by PRMT5 or WDR77. The 'Description' variable summarizes the biological process, molecular function, or cellular component of the gene it represents. The 'FDR' variable is the adjusted p-value that estimates the proportion of significant results that may be false positives. The 'Enrichment' variable indicates the fold-enrichment value representing how a GO term is compared to what would be expected by chance."
)
)
}) |>
bindEvent(input$show)

}

shinyApp(ui, server)
```


```{r, echo=FALSE}
renderDataTable({
  datatable(GO_widget,
            filter = list(position = "top", clear = FALSE, plain = TRUE),
            extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           pageLength = 10,
                           buttons = list(extend='collection',
                                          buttons=c('csv', 'excel'),
                                          text='Download'))
  ) %>%
    formatSignif(columns=c('FDR', 'Enrichment'), digits=4)
})
```

## to compare <GO:ID> gene stuff

```{r, echo = FALSE}

selectInput("go_selector", 
            "Select a GO ID (start typing to find GO ID)", 
            choices = unique(GO_gene$`GO Term`), 
            multiple = FALSE, 
            selected = "GO:0000041")

inputPanel(
  sliderInput(inputId = "max_genes", 
              label = "Choose maximum number of genes.", 
              min = 1, 
              max = 50, 
              value = 10),
  downloadButton("download_plot", "Download Plot")
)

plot_reactive <- reactive({

  req(input$go_selector)



  target_symbols <- geneIndex %>% 
    filter(GO_ID == input$go_selector) %>% 
    pull(Symbol) %>% 
    unique()

  plot_data <- RNAseq %>% 
    filter(SYMBOL %in% target_symbols)

  top_genes <- plot_data %>%
    group_by(SYMBOL) %>%
    summarize(max_change = max(abs(logFC))) %>%
    arrange(desc(max_change)) %>%
    slice_head(n = input$max_genes) %>%
    pull(SYMBOL)

  GO_column <- plot_data %>%
    filter(SYMBOL %in% top_genes) %>%
    ggplot(aes(x = reorder(SYMBOL, SYMBOL), y = logFC, fill = silenced)) +
    geom_col(position = "dodge") + 
    coord_flip() +
    labs(title = paste("Results for Top", input$max_genes, "Genes for", input$go_selector),
         x = "SYMBOL", 
         y = "logFC") +
    scale_fill_hue(labels = c("PRMT5", "WDR77")) +
    theme_gray() +
    theme(text = element_text(size = 14))
  
  return(GO_column)
})


renderPlot({
  plot_reactive()
})

output$download_plot <- downloadHandler(
  filename = function() {
    clean_name <- gsub(":", "_", input$go_selector)
    paste("GO_Analysis_", clean_name, ".png", sep = "")
  },
  content = function(file){
    ggsave(file, plot = plot_reactive(), device = "png", width = 14, height = 8)
  }
)


```

## Heatmap widget

```{r, echo=FALSE}
go_to_symbols <- mep50_geneIndex %>%
  rbind(prmt5_geneIndex) %>%
  select(-grouping)

go_to_symbols
```

```{r, echo=FALSE}
GOIDs <- go_to_symbols %>%
  distinct(GO_ID) %>%
  pull(GO_ID)
```

```{r, echo=FALSE}
cpm_mat <- as.matrix(cpm)
```

```{r, echo=FALSE}
selectInput("GOID", "Select one or more GOIDs. Start typing...", choices = GOIDs, multiple = TRUE, selected = "GO:0000041", selectize = TRUE)
selectInput("clSam", "Cluster by Sample?", choices = c("TRUE", "FALSE"), selected = "FALSE", selectize = TRUE)
selectInput("clGene", "Cluster by Gene?", choices = c("TRUE", "FALSE"), selected = "FALSE", selectize = TRUE)
selectInput("distanceSam", "Distance Method for Samples", choices = c("euclidean", "manhattan"), selected = "euclidean", selectize = TRUE)
selectInput("distanceGene", "Distance Method for Genes", choices = c("euclidean", "manhattan"), selected = "euclidean", selectize = TRUE)
selectInput("linkage", "Linkage Method for All Clustering", choices = c("single", "complete", "average"), selected= "average", selectize = TRUE)
selectInput("scale", "Method of Data Scaling (Row for Gene, Column for Sample)", choices = c("none", "row", "column"), selected = "none", selectize = TRUE)
```

```{r, echo=FALSE}

renderPlot({
  req(input$GOID, input$distanceSam,
      input$distanceGene, input$linkage, input$scale)
  selected_genes <- go_to_symbols %>%
    filter(GO_ID %in% input$GOID) %>%
    pull(Symbol) %>%
    unique()
  cpm_sub <- cpm_mat[cpm_mat[,1] %in% selected_genes, ,drop = FALSE]
  cpm_numeric <- apply(cpm_sub[,-1,drop=FALSE], 2, function(x) as.numeric(trimws(x)))
  rownames(cpm_numeric) <- cpm_sub[,1]
  pheatmap(cpm_numeric, scale = input$scale, 
           cluster_rows = as.logical(input$clGene), 
           cluster_cols = as.logical(input$clSam), 
           clustering_distance_rows = input$distanceGene, 
           clustering_distance_cols = input$distanceSam,
           clustering_method = input$linkage)
}, 
res = 150, 
height = function(){
  max(1200, nrow(heat_genes()) * 12)
}, 
width = 1200
)
```
